### ISSUE TITLE
Sound From headphone and speaker at same time

### ISSUE THREAD

**Issue by AzizKamboh** [shibajee/realtek-uad-nahimic-mod#1]
Hey, i installed this driver, every thing works but sound keeps coming from speakers even after headphone is connected, sound keeps coming from headphone and laptop speakers at the same time. I have HP Probook 450 G2, and my laptop has DTS Sound+ control panel by default if no modded driver is installed.

**Comment by shibajee** [comment]
Open realtek audio console from start menu and click on Device advanced settings then on Playback device what option u have ? @AzizKamboh
