### ISSUE TITLE
error after reinstalling

### ISSUE THREAD

**Issue by trinib** [shibajee/realtek-uad-nahimic-mod#11]
i tired everything ..how to fix ?
![image](https://user-images.githubusercontent.com/18756975/105081762-fba62380-5a68-11eb-9190-ea0b950cbca7.png)

**Comment by trinib** [comment]
well the only way i could fix is reinstalling windows 🤣😂..guess was my fault for not turning off windows store updates..

**Comment by shibajee** [comment]
> well the only way i could fix is reinstalling windows ..guess was my fault for not turning off windows store updates..

This error code 0xE000022F means u r not on disable driver enforcement mode. You did a very basic mistake. @trinib

**Comment by trinib** [comment]
hmm I did that over and over..
