### ISSUE TITLE
Error 0xc00d36b4

### ISSUE THREAD

**Issue by imacpr0** [shibajee/realtek-uad-nahimic-mod#2]
Any avi playback in Movies and TV app (windows 10 1909) give error
0xc00d36b4. Turning off enable audio enhancements in speaker properties helps.
But nahimic does not work in this case. Media player does not work also. VLC works fine. 
Checked on 2 notebooks with different codecs.
Do you have this "feature" ?

**Comment by shibajee** [comment]
Can u follow this procedure https://help.netflix.com/en/node/53402 ? See if this works or not. It's for netflix app but It should work with this problems too. If this works pls comment and I'll update the fix in next release. @imacpr0

**Comment by imacpr0** [comment]
No, it is not help. Maybe this is because driver is unsigned ?
https://technet.microsoft.com/en-us/ff538609(v=vs.96). My notebooks are old enough. Cannot find
signed drivers to check.
