### ISSUE TITLE
Realtek Audio Console closes after launch

### ISSUE THREAD

**Issue by SergeyTverye** [shibajee/realtek-uad-nahimic-mod#6]
Hi! My Windows auto updated the sound driver, so I had to reinstall your mod. I deleted everything through the control panel, carefully cleaned up the traces in the registry and in the files. And now Realtek Audio Console closes immediately after launch, although Nahimic works well. I don’t understand why it happened and already reinstalled everything twice. I hope that the next update will be able to fix this. Thanks so much for your work! :)

**Comment by shibajee** [comment]
install the latest version, see if the problem still happens @SergeyTverye

**Comment by epman100** [comment]
disable windows 10 auto updates if it auto updated the realtek audio driver, overwriting the modded realtek driver.
also before installing modded realtek nahimic driver, disconnect from the internet (that means turning off wifi, enabling "airplane mode" or unplugging the ethernet/LAN cable).  must install modded driver "offline"

also establish an internet connection after installing modded realtek driver and before launching realtek audio console as that app sometimes requires an active internet connection or it may immediately close after launch.
