### ISSUE TITLE
Netflix Error U7361-1253-C00D36B4

### ISSUE THREAD

**Issue by attafwrd** [shibajee/realtek-uad-nahimic-mod#7]
Can't play Netflix audio using Netflix App from Store.
Gives "Netflix Error U7361-1253-C00D36B4".
Probably protected audio?
Disabling audio enhancements from Windows 10 Sound control panel fixes it.
Any workarounds?

**Comment by shibajee** [comment]
Even in their official [knowledgebase](https://help.netflix.com/en/node/39917) they suggest to disable audio enhancement, probably don't support nahimic enhancement in the app yet. @ATTAFWRD

**Comment by attafwrd** [comment]
Noted, kind sir. Thank you for the positive reply!
